openapi: 3.0.2
info:
  description: Searching of WorldCat
  version: 2.0.0
  title: WorldCat Search API v. 2
servers:
  - url: 'https://americas.discovery.api.oclc.org/worldcat/search/v2'
security:
  - worldcat_search_auth:
      - wcapi
paths:
  /bibs-retained-holdings:
    get:
      tags:
        - Member Shared Print Holdings
      summary: Find member shared print holdings for a known item
      description: 'Given a known item, find the member library holdings with a commitment to retain (Shared Print)'
      operationId: find-bib-retained-holdings
      security:
        - worldcat_search_auth:
            - 'wcapi:view_retained_holdings'
  /bibs-summary-holdings:
    get:
      tags:
        - Member General Holdings
      summary: Get summary of holdings for a known item
      description: 'Given a known item, get summary of holdings'
      operationId: find-bib-summary-holdings
      security:
        - worldcat_search_auth:
            - 'wcapi:view_summary_holdings'
  /bibs-holdings:
    get:
      tags:
        - Member General Holdings
      summary: Find member holdings for a known item
      description: 'Given a known item, find the member libraries who hold it'
      operationId: find-bib-holdings
      security:
        - worldcat_search_auth:
            - 'wcapi:view_institution_holdings'
  /bibs-detailed-holdings:
    get:
      tags:
        - Member General Holdings
      summary: Find detailed info of member holdings for a known item
      description: 'Given a known item, search member library holdings for detailed information'
      operationId: find-bib-detailed-holdings
      security:
        - worldcat_search_auth:
            - 'wcapi:view_holdings'
  /bibs:
    get:
      tags:
        - Bibliographic Resources
      summary: Search Bibliographic Resources
      description: |
        Search Bibliographic Resources. Key Indexes <table cellspacing="0"> <tbody><tr><th>Index Name</th> <th>Index Code</th> </tr> <tr><td>Author</td> <td>au</td> </tr><tr><td>Corporate/Conference Name</td> <td>cn</td> </tr><tr><td>ISBN</td> <td>bn</td> </tr><tr><td>ISSN</td> <td>in</td> </tr><tr><td>Keyword</td> <td>kw</td> </tr><tr><td>LCCN</td> <td>dn</td> </tr><tr><td>Notes</td> <td>nt</td> </tr><tr><td>OCLC Number</td> <td>sno</td> </tr><tr><td>Place of publication</td> <td>pl</td> </tr><[...]       
      operationId: search-bibs
      security:
        - worldcat_search_auth:
            - 'wcapi:view_bib'
  '/bibs/{oclcNumber}':
    get:
      tags:
        - Bibliographic Resources
      summary: Retrieve specific Bibliographic Resource
      description: Retrieve specific Bibliographic Resource
      operationId: retrieve-bib
      security:
        - worldcat_search_auth:
            - 'wcapi:view_bib'
  /brief-bibs:
    get:
      tags:
        - Bibliographic Resources
      summary: Search Brief Bibliographic Resources
      description: |
        Search Bibliographic Resources. Key Indexes <table cellspacing="0"> <tbody><tr><th>Index Name</th> <th>Index Code</th> </tr> <tr><td>Author</td> <td>au</td> </tr><tr><td>Corporate/Conference Name</td> <td>cn</td> </tr><tr><td>ISBN</td> <td>bn</td> </tr><tr><td>ISSN</td> <td>in</td> </tr><tr><td>Keyword</td> <td>kw</td> </tr><tr><td>LCCN</td> <td>dn</td> </tr><tr><td>Notes</td> <td>nt</td> </tr><tr><td>OCLC Number</td> <td>sno</td> </tr><tr><td>Place of publication</td> <td>pl</td> </tr><[...]       
      operationId: search-brief-bibs
      security:
        - worldcat_search_auth:
            - 'wcapi:view_brief_bib'
  '/brief-bibs/{oclcNumber}':
    get:
      tags:
        - Bibliographic Resources
      summary: Retrieve specific Bibliographic Resource
      description: Retrieve specific Bibliographic Resource
      operationId: retrieve-brief-bib
      security:
        - worldcat_search_auth:
            - 'wcapi:view_brief_bib'
  '/brief-bibs/{oclcNumber}/other-editions':
    get:
      tags:
        - Bibliographic Resources
      summary: Retrieve Other Editions related to a particular Bibliographic Resource
      description: Retrieve Other Editions related to a particular Bibliographic Resource
      operationId: retrieve-other-editions
      security:
        - worldcat_search_auth:
            - 'wcapi:view_brief_bib'
  '/my-holdings/{controlNumber}':
    get:
      tags:
        - Local Holdings Resources
      summary: Retrieve LHR Resource
      description: Retrieve LHR Resource
      operationId: retrieve-lhr
      security:
        - worldcat_search_auth:
            - 'wcapi:view_my_holdings'
  /my-holdings:
    get:
      tags:
        - Local Holdings Resources
      summary: Search LHR Resources
      description: Search LHR Resources
      operationId: search-lhr
      security:
        - worldcat_search_auth:
            - 'wcapi:view_my_holdings'
  /retained-holdings:
    get:
      tags:
        - Local Holdings Resources
      summary: Search for shared print LHR Resources
      description: Search for shared print LHR Resources
      operationId: search-retrained-lhr
      security:
        - worldcat_search_auth:
            - 'wcapi:view_retained_holdings'
components:
  securitySchemes:
    worldcat_search_auth:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: 'https://oauth.oclc.org/token'
          scopes:
            wcapi: perform all the operation in the WorldCat Search API
            'wcapi:view_bib': view bibliographic data
            'wcapi:view_brief_bib': view brief bibliographic data
            'wcapi:view_retained_holdings': view holdings which libraries have chosen to retain
            'wcapi:view_summary_holdings': view summary information about library holdings
            'wcapi:view_my_holdings': view detailed information about the authentication institution's holdings
            'wcapi:view_institution_holdings': view information about what library holds an item
            'wcapi:view_holdings': view detailed information about library holdings
        authorizationCode:
          authorizationUrl: 'https://oauth.oclc.org/auth'
          tokenUrl: 'https://oauth.oclc.org/token'
          scopes:
            wcapi: perform all the operation in the Discovery domain
            'wcapi:view_bib': view bibliographic data
            'wcapi:view_brief_bib': view brief bibliographic data
            'wcapi:view_retained_holdings': view holdings which libraries have chosen to retain
            'wcapi:view_summary_holdings': view summary information about library holdings
            'wcapi:view_my_holdings': view detailed information about the authentication institution's holdings
            'wcapi:view_institution_holdings': view information about what library holds an item
            'wcapi:view_holdings': view detailed information about library holdings