// From: https://help-nl.oclc.org/Discovery_and_Reference/WorldCat_Discovery/Search_results/Format_display_in_search_results?sl=nl
export const formats = {
  Archv: "Archival Material",
  ArtChapter: "Article",
  AudioBook: "Audiobook",
  Book: "Book",
  CompFile: "Computer File",
  Encyc: "Encyclopedia",
  Game: "Game",
  Image: "Image",
  IntMM: "Interactive Multimedia",
  Jrnl: "Journal/Magazine",
  Kit: "Kit",
  Map: "Map",
  MsScr: "Musical Score",
  Music: "Music Recording",
  News: "Newspaper",
  Object: "Object",
  Snd: "Sound Recording",
  Toy: "Toy",
  Video: "Video",
  Vis: "Visual material",
  Web: "Internet Resource",
};
